[book]
authors = ["yexiyue"]
language = "zh"
multilingual = false
src = "src"
title = "dialogue macro"

[output.html]
additional-js = ["theme/custom/main.js"]
additional-css = ["theme/custom/translate.css"]
git-repository-url = "https://github.com/yexiyue/dialogue-macro"
